<fieldset class="fieldset create account" data-hasrequired="<?php /* @escapeNotVerified */echo __('* Required Fields') ?>">
    <legend class="legend">
        <span><?php /* @escapeNotVerified */echo __('Additional Information') ?></span>
    </legend>
    <br>
    <div class="field phone_number required">
        <label class="label" for="email">
            <span><?= $block->escapeHtml(__('Phone Number')) ?></span>
        </label>
        <div class="control">
            <input type="text"
                   name="phone_number"
                   id="phone_number"
                   title="<?php /* @escapeNotVerified */echo __('Phone number') ?>"
                   class="input-text"
                   data-validate="{required:true}"
                   autocomplete="off">
        </div>
    </div>
</fieldset>